FROM node:current-alpine

WORKDIR /frontend/

ENV PATH /groupthinq_frontend/node_modules/.bin:$PATH

COPY /groupthinq_frontend/package.json /frontend/package.json
RUN npm install
RUN npm install -g @vue/cli
RUN npm install -g @quasar/cli

WORKDIR /frontend/groupthinq_frontend

CMD ["quasar", "dev"]