CREATE TABLE USERS (
USERNAME VARCHAR(32) UNIQUE PRIMARY KEY NOT NULL,
LASTNAME VARCHAR(32) NOT NULL,
FIRSTNAME VARCHAR(32) NOT NULL,
EMAIL VARCHAR(32) NOT NULL );

INSERT INTO USERS VALUES ('jsmith', 'Smith', 'John', 'jsmith@foo.com');
INSERT INTO USERS VALUES ('mboyer', 'Boyer', 'Matt', 'mboyer87@gmail.com');
INSERT INTO USERS VALUES ('testuser', 'User', 'Test', 'testUser@foo.bar');
INSERT INTO USERS VALUES ('treyob', 'Reyob', 'Ttam', 'ttamreyob@gmail.com');

CREATE TABLE DECISION (
    ID INTEGER UNIQUE PRIMARY KEY NOT NULL,
    NAME VARCHAR(32) NOT NULL
);

INSERT INTO DECISION VALUES (1, 'TEST DECISION 1');
INSERT INTO DECISION VALUES (2, 'TEST DECISION 2');
INSERT INTO DECISION VALUES (3, 'TEST DECISION 3');
INSERT INTO DECISION VALUES (4, 'TEST DECISION 4');
INSERT INTO DECISION VALUES (5, 'TEST DECISION 5');

CREATE TABLE DECISION_USERS (
    ID INTEGER UNIQUE PRIMARY KEY NOT NULL,
    DECISION_ID INTEGER REFERENCES DECISION(ID) NOT NULL,
    USERNAME VARCHAR(32) REFERENCES USERS(USERNAME) NOT NULL
);

INSERT INTO DECISION_USERS VALUES (1, 1, 'jsmith');
INSERT INTO DECISION_USERS VALUES (2, 2, 'jsmith');
INSERT INTO DECISION_USERS VALUES (3, 2, 'mboyer');
INSERT INTO DECISION_USERS VALUES (4, 2, 'testuser');
INSERT INTO DECISION_USERS VALUES (5, 2, 'treyob');
INSERT INTO DECISION_USERS VALUES (6, 3, 'mboyer');
INSERT INTO DECISION_USERS VALUES (7, 4, 'jsmith');
INSERT INTO DECISION_USERS VALUES (8, 5, 'jsmith');
INSERT INTO DECISION_USERS VALUES (9, 5, 'mboyer');