# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Database CD to Staging DB

on:
  push:
    branches: [ staging ]

jobs:
  migrate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upload SQL File
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: sweng894-gp4-cap
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: cp ./database/scripts/setup.sql gs://db-sql-staging/
        cli: gsutil

    - name: Delete Database
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: sweng894-gp4-cap
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: sql databases delete groupthinq --instance=groupthinq-db-staging
        cli: gcloud

    - name: Add Database
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: sweng894-gp4-cap
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: sql databases create groupthinq --instance=groupthinq-db-staging
        cli: gcloud

    - name: Import SQL
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: sweng894-gp4-cap
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: sql import sql groupthinq-db-staging gs://db-sql-staging/setup.sql --database=groupthinq
        cli: gscloud